Vagrant.require_version ">= 2.3.7", "<= 2.4.1"

Vagrant.configure("2") do |config|
  config.vm.define "semaphore" do |semaphore|
    semaphore.vm.hostname = "semaphore"
    semaphore.vm.box = "bento/ubuntu-22.04"
    semaphore.vm.box_version = "202407.23.0"
    semaphore.vm.box_check_update = true
    semaphore.vm.network "public_network", ip: "192.168.18.10", bridge: "wlp3s0"
    
    semaphore.vm.provider "virtualbox" do |v|
      v.name = "semaphore"
      v.memory = "4096"
      v.cpus = 4
    end
  end
end
