Vagrant.require_version ">= 2.3.7", "<= 2.4.1"
Vagrant.configure("2") do |config|

  config.vm.define "master" do |master|
    master.vm.box = "master"
    master.vm.box = "ubuntu/trusty64"
    master.vm.box_version = "20191107.0.0"
    master.vm.box_check_update = true
    master.vm.network "forwarded_port", guest: 80, host: 8080
    master.vm.network "private_network", type: "dhcp"
    
    master.vm.provider "virtualbox" do |v|
      v.name = "master-01"
      v.memory = "1024"
    end
  end

  (1..3).each do |i|
    config.vm.define "work-0#{i}" do |work|
      vm_name = "work-0#{i}"
      work.vm.hostname = "elliot-0#{i}"
      work.vm.box = "ubuntu/trusty64"
      work.vm.box_version = "20191107.0.0"
      work.vm.box_check_update = true
      work.vm.network "private_network", type: "dhcp"
  
      work.vm.provider "virtualbox" do |v|
        v.name = "work-0#{i}"
      end
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
  end
end