Vagrant.require_version ">= 2.3.7", "<= 2.4.1"
Vagrant.configure("2") do |config|

  # Multiples Machines
  config.vm.define "master" do |master|
    master.vm.box = "master"
    master.vm.box = "ubuntu/trusty64"
    master.vm.box_version = "20191107.0.0"
    master.vm.box_check_update = true
    master.vm.network "forwarded_port", guest: 80, host: 8080
    master.vm.network "private_network", type: "dhcp"
    #master.memory = "1024"
  end
#
  config.vm.define "work" do |work|
    work.vm.box = "work"
    work.vm.box = "ubuntu/trusty64"
    work.vm.box_version = "20191107.0.0"
    work.vm.box_check_update = true
    #work.vm.network "forwarded_port", guest: 80, host: 8080
    work.vm.network "private_network", type: "dhcp"
    #work.memory = "1024"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = 2
 end
  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
